### ISSUE TITLE
BMS tutorial should say how we can obtain a text/latex representation from the model

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora-theorist-bms#10]

**Comment by benwandrew** [comment]
@TheLemonPig is this something you can add (or already have added)?

**Comment by TheLemonPig** [comment]
Yes, this is an easy fix (single command) which I will add to the notebook today

**Comment by benwandrew** [comment]
> Yes, this is an easy fix (single command) which I will add to the notebook today

great, thanks! can you do so by creating a branch linked to this issue ("Create a branch" on the right side of this page) and then a corresponding PR?

**Comment by TheLemonPig** [comment]
I accidentally added this first to a PR I made for the AI institute on the autora repo. I notice there are two ways to access the tutorial for BMS: one on the autora repo and one on this autora-theorist-bms repo. Are these two notebooks the same, or will updating one not necessarily update the other? I notice the two notebooks have different names which makes me think they may be two completely different notebooks.

**Comment by benwandrew** [comment]
it's a little complicated at present because we are using BMS as a stand-in for our [general Theorist tutorial](https://autoresearch.github.io/autora/tutorials/Theorist/), but I think that will eventually not be the case (no one has created a general theorist tutorial yet, but I think it's a to-do). The specific [BMS documentation under User Guide](https://autoresearch.github.io/autora/user-guide/theorists/bms/) should be the same as that in the BMS-specific repo, however, since that is just a direct import in the parent `mkdocs.yml`


<img width="823" alt="Screen Shot 2023-06-30 at 08 50 06" src="https://github.com/AutoResearch/autora-theorist-bms/assets/28738595/2faa4c83-88ce-492a-9690-787fb608aa8f">

**Comment by benwandrew** [comment]
so in general, you should make changes to the BMS-specific repo/package
